import fs from 'node:fs/promises';
const root=new URL('../artifacts/screenshots/',import.meta.url).pathname;
const {screens}=JSON.parse(await fs.readFile(root+'manifest.json','utf8'));
const sourceScreens=[['01-search-over-inspector','Search · Focus & grouped results'],['02-expanded-inspector','Issue · Expanded inspector'],['03-viewed-file','Review · Viewed files'],['04-pending-review','Review · Private drafts'],['05-log-fields','Logs · Include / exclude fields'],['06-log-json','Logs · Same-event JSON'],['07-surrounding-logs','Logs · Surrounding events'],['08-log-fields-dark','Logs · Field filters in dark mode'],['09-search-dark','Search · Dark mode']];
for(const [id,title] of sourceScreens){try{await fs.access(root+'../source-review/'+id+'.png');screens.push({id:'oss-'+id,title,group:'Source-informed improvements',file:'../source-review/'+id+'.png'})}catch{}}
const visualScreens=[['01-dependency-flow','MR · Dependency flow'],['02-sequence','MR · Sequence diagram'],['03-code-comment','MR · Source code & inline comment'],['04-ai-guide','MR · AI review guide'],['05-ai-guide-dark','MR · AI guide / Dark'],['06-dependency-dark','MR · Dependency flow / Dark'],['07-gitlab-settings','GitLab · Domain & token'],['08-jira-settings','Jira Cloud · URL & API token'],['09-wiki-settings','Confluence · URL & API token'],['10-claude-settings','Claude · Anthropic endpoint'],['11-connected-home','Connected workspace']];
for(const [id,title] of visualScreens){try{await fs.access(root+'../visual-review/'+id+'.png');screens.push({id:'visual-'+id,title,group:'Visual review & live integrations',file:'../visual-review/'+id+'.png'})}catch{}}
try{const connected=JSON.parse(await fs.readFile(root+'../connected-workflows/manifest.json','utf8'));screens.push(...connected.screens.map(s=>({...s,id:'connected-'+s.id})));}catch{}
const groups=[...new Set(screens.map(s=>s.group))];
const html=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Worklane — 전체 화면 스크린샷</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f6f7;color:#24363a;font:14px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}header{padding:34px 40px 24px;background:white;border-bottom:1px solid #dfe5e7;position:sticky;top:0;z-index:2}h1{font-size:26px;letter-spacing:-1px;margin:0 0 10px}p{color:#77858a;font-size:13px;margin:0}nav{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}nav a{padding:7px 11px;background:#f2f5f5;color:#476763;border-radius:5px;text-decoration:none;font-size:12px}nav a:hover{background:#dfebe7}main{max-width:1800px;margin:auto;padding:20px 40px 70px}section{scroll-margin-top:185px}h2{font-size:17px;margin:28px 0 18px;font-weight:550}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px}figure{margin:0}figure button{padding:0;border:1px solid #d7dfe1;background:white;display:block;cursor:zoom-in;width:100%;border-radius:6px;overflow:hidden;box-shadow:0 3px 10px #18372d05;transition:box-shadow .15s}figure button:hover{box-shadow:0 6px 22px #18372d20;border-color:#7dada0}figure img{display:block;width:100%;height:auto;aspect-ratio:1.6}figcaption{display:flex;gap:10px;padding:11px 2px;font-size:12px;line-height:1.5}figcaption b{font-weight:400;color:#95a2a6}dialog{padding:0;border:0;border-radius:8px;max-width:98vw;width:1480px;background:#182127;color:#e8efef;box-shadow:0 20px 90px #0008}dialog::backdrop{background:#111b27cd}dialog img{width:100%;display:block;max-height:82vh;object-fit:contain}dialog .bar{display:flex;gap:16px;align-items:center;padding:12px 18px;font-size:13px}dialog .bar span{flex:1}dialog button,dialog a{border:1px solid #4b626a;border-radius:4px;color:#e8efef;background:none;padding:7px 11px;cursor:pointer;text-decoration:none;font-size:12px}button:focus-visible,a:focus-visible{outline:3px solid #54a292;outline-offset:3px}.hint{font-size:11px;color:#a6b8bb;margin-left:10px}@media(max-width:1100px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:680px){header{padding:20px;position:static}.grid{grid-template-columns:1fr}main{padding:10px 20px 40px}.hint{display:none}dialog .bar{gap:6px}}
</style><header><h1>Worklane — 전체 화면 스크린샷</h1><p>실제 실행 화면 ${screens.length}장 · 1440 × 900 · 이미지를 클릭하면 원본 확대 · 확대 후 ← → 키로 이동</p><nav>${groups.map((g,i)=>`<a href="#group-${i}">${g==='Core'?'핵심 화면':g}</a>`).join('')}<a href="../orbit-all-screenshots.zip" download>전체 ZIP 다운로드</a></nav></header><main>${groups.map((g,i)=>`<section id="group-${i}"><h2>${g==='Core'?'핵심 화면':g}</h2><div class="grid">${screens.filter(s=>s.group===g).map(s=>`<figure><button data-id="${s.id}" aria-label="${s.title} 확대"><img src="${s.file}" alt="${s.title}" loading="lazy"></button><figcaption><b>${s.id.slice(0,2)}</b>${s.title}</figcaption></figure>`).join('')}</div></section>`).join('')}</main><dialog id="viewer"><div class="bar"><button id="prev" aria-label="이전 화면">←</button><button id="next" aria-label="다음 화면">→</button><span id="caption"></span><a id="original" target="_blank">원본</a><button id="close">닫기 ✕</button></div><img id="large" alt=""></dialog><script>
const screens=${JSON.stringify(screens)};let current=0;const viewer=document.getElementById('viewer');function show(i){current=(i+screens.length)%screens.length;const s=screens[current];document.getElementById('large').src=s.file;document.getElementById('large').alt=s.title;document.getElementById('caption').textContent=(current+1)+' / '+screens.length+' — '+s.title;document.getElementById('original').href=s.file;if(!viewer.open)viewer.showModal()};document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>show(screens.findIndex(s=>s.id===b.dataset.id)));document.getElementById('prev').onclick=()=>show(current-1);document.getElementById('next').onclick=()=>show(current+1);document.getElementById('close').onclick=()=>viewer.close();document.addEventListener('keydown',e=>{if(viewer.open&&e.key==='ArrowRight')show(current+1);if(viewer.open&&e.key==='ArrowLeft')show(current-1)});viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close()});
</script></html>`;
await fs.writeFile(root+'index.html',html);
