export const initialIssues = [
  {
    id: "PAY-382",
    title: "Payment retry implementation",
    status: "In Progress",
    priority: "High",
    assignee: "Alex Kim",
    sprint: "Sprint 24",
    due: "2025-10-03",
    day: "Fri",
    mr: "381",
    project: "PAY",
    description:
      "Retry failed payment requests with exponential backoff. Preserve idempotency across retries and send exhausted attempts to the dead-letter queue.",
    subtasks: [
      "Add exponential backoff strategy",
      "Persist idempotency keys",
      "Cover retry exhaustion with integration tests",
    ],
  },
  {
    id: "API-128",
    title: "Order API refactoring",
    status: "Todo",
    priority: "Medium",
    assignee: "Alex Kim",
    sprint: "Sprint 24",
    due: "2025-10-03",
    day: "Fri",
    mr: "391",
    project: "API",
    description:
      "Separate order status mapping from the controller layer. Align the public response schema with the v2 API contract.",
  },
  {
    id: "OPS-91",
    title: "Production error investigation",
    status: "In Progress",
    priority: "Urgent",
    assignee: "Sarah Park",
    sprint: "Sprint 24",
    due: "2025-10-03",
    day: "Fri",
    mr: "376",
    project: "OPS",
    description:
      "Investigate elevated 502 responses in payment-api after the 08:32 deployment. Correlate traces with connection pool saturation.",
  },
  {
    id: "PAY-291",
    title: "Validate webhook signature handling",
    status: "In Review",
    priority: "High",
    assignee: "Alex Kim",
    sprint: "Sprint 24",
    due: "2025-10-04",
    day: "Sat",
    mr: "384",
    project: "PAY",
    description:
      "Verify webhook signatures before processing payment events. Include replay protection and a five-minute timestamp tolerance.",
  },
  {
    id: "API-124",
    title: "Add cursor pagination to orders",
    status: "Done",
    priority: "Medium",
    assignee: "Alex Kim",
    sprint: "Sprint 24",
    due: "2025-10-02",
    day: "Thu",
    mr: "372",
    project: "API",
  },
  {
    id: "PAY-378",
    title: "Payment timeout configuration",
    status: "Done",
    priority: "High",
    assignee: "Daniel Lee",
    sprint: "Sprint 24",
    due: "2025-10-01",
    day: "Wed",
    mr: "376",
    project: "PAY",
  },
  {
    id: "OPS-88",
    title: "Update on-call runbook",
    status: "Todo",
    priority: "Low",
    assignee: "Alex Kim",
    sprint: "Backlog",
    due: "",
    day: "Backlog",
    mr: "",
    project: "OPS",
  },
  {
    id: "API-132",
    title: "Document order state transitions",
    status: "Todo",
    priority: "Low",
    assignee: "Alex Kim",
    sprint: "Backlog",
    due: "",
    day: "Backlog",
    mr: "",
    project: "API",
  },
  {
    id: "PAY-386",
    title: "Handle duplicate capture requests",
    status: "Todo",
    priority: "Medium",
    assignee: "Mina Choi",
    sprint: "Sprint 24",
    due: "2025-10-06",
    day: "Mon",
    mr: "",
    project: "PAY",
  },
  {
    id: "OPS-85",
    title: "Tune connection pool alerts",
    status: "Done",
    priority: "Medium",
    assignee: "Sarah Park",
    sprint: "Sprint 24",
    due: "2025-09-30",
    day: "Tue",
    mr: "",
    project: "OPS",
  },
  {
    id: "API-119",
    title: "Remove deprecated order endpoint",
    status: "Done",
    priority: "Low",
    assignee: "Daniel Lee",
    sprint: "Sprint 24",
    due: "2025-09-29",
    day: "Mon",
    mr: "369",
    project: "API",
  },
  {
    id: "PAY-374",
    title: "Add payment audit events",
    status: "Done",
    priority: "Medium",
    assignee: "Mina Choi",
    sprint: "Sprint 24",
    due: "2025-10-01",
    day: "Wed",
    mr: "370",
    project: "PAY",
  },
];
export const initialMRs = [
  {
    id: "391",
    title: "Fix order status mapping",
    repo: "order-api",
    author: "Daniel Lee",
    status: "Review requested",
    ci: "Passed",
    comments: 3,
    updated: "18h ago",
    issue: "API-128",
    files: 4,
    added: 86,
    removed: 24,
  },
  {
    id: "381",
    title: "Payment retry handling",
    repo: "payment-api",
    author: "Alex Kim",
    status: "In review",
    ci: "Passed",
    comments: 6,
    updated: "42m ago",
    issue: "PAY-382",
    files: 4,
    added: 142,
    removed: 38,
  },
  {
    id: "384",
    title: "Verify webhook signatures before processing",
    repo: "payment-api",
    author: "Mina Choi",
    status: "Review requested",
    ci: "Running",
    comments: 2,
    updated: "2h ago",
    issue: "PAY-291",
    files: 3,
    added: 94,
    removed: 12,
  },
  {
    id: "376",
    title: "Configure payment connection pool",
    repo: "payment-api",
    author: "Daniel Lee",
    status: "Merged",
    ci: "Passed",
    comments: 4,
    updated: "Yesterday",
    issue: "PAY-378",
    files: 2,
    added: 32,
    removed: 16,
  },
  {
    id: "372",
    title: "Cursor-based pagination for orders",
    repo: "order-api",
    author: "Alex Kim",
    status: "Merged",
    ci: "Passed",
    comments: 1,
    updated: "Yesterday",
    issue: "API-124",
    files: 6,
    added: 181,
    removed: 47,
  },
  {
    id: "369",
    title: "Remove legacy order endpoints",
    repo: "order-api",
    author: "Daniel Lee",
    status: "Merged",
    ci: "Passed",
    comments: 2,
    updated: "Mon",
    issue: "API-119",
    files: 8,
    added: 12,
    removed: 226,
  },
];
export const documents = [
  {
    id: "retry-policy",
    title: "Payment Retry Policy",
    space: "Engineering",
    updated: "Oct 2",
    author: "Mina Choi",
    issue: "PAY-382",
  },
  {
    id: "order-contract",
    title: "Order API v2 contract",
    space: "Engineering",
    updated: "Oct 1",
    author: "Daniel Lee",
    issue: "API-128",
  },
  {
    id: "runbook",
    title: "Payment service runbook",
    space: "Operations",
    updated: "Sep 30",
    author: "Sarah Park",
    issue: "OPS-91",
  },
  {
    id: "postmortem",
    title: "September payment latency review",
    space: "Operations",
    updated: "Sep 26",
    author: "Sarah Park",
    issue: "OPS-91",
  },
  {
    id: "onboarding",
    title: "Backend engineering handbook",
    space: "Getting started",
    updated: "Sep 24",
    author: "Alex Kim",
    issue: "API-128",
  },
];
export const members = [
  { name: "Alex Kim", role: "Backend engineer", initials: "AK", color: "teal" },
  {
    name: "Sarah Park",
    role: "Site reliability engineer",
    initials: "SP",
    color: "purple",
  },
  {
    name: "Daniel Lee",
    role: "Backend engineer",
    initials: "DL",
    color: "blue",
  },
  {
    name: "Mina Choi",
    role: "Software engineer",
    initials: "MC",
    color: "amber",
  },
];
export const events = [
  {
    id: "daily",
    title: "Daily standup",
    time: "09:00",
    end: "09:15",
    day: "Fri",
    room: "Backend team · Huddle",
    people: 4,
  },
  {
    id: "backend",
    title: "Backend sync",
    time: "11:30",
    end: "12:00",
    day: "Fri",
    room: "Engineering · Room 3",
    people: 6,
  },
  {
    id: "planning",
    title: "Sprint planning",
    time: "14:00",
    end: "15:00",
    day: "Fri",
    room: "Product & Engineering · Room 2",
    people: 8,
  },
  {
    id: "retro",
    title: "Sprint retrospective",
    time: "16:00",
    end: "16:45",
    day: "Thu",
    room: "Backend team · Room 2",
    people: 6,
  },
  {
    id: "design",
    title: "API design review",
    time: "10:00",
    end: "11:00",
    day: "Tue",
    room: "Engineering · Room 3",
    people: 4,
  },
];
export const logs = Array.from({ length: 32 }, (_, i) => ({
  id: "log-" + i,
  time: `09:${String(42 - Math.floor(i / 4)).padStart(2, "0")}:${String(58 - ((i * 7) % 59)).padStart(2, "0")}.${String(281 + i * 17).padStart(3, "0")}`,
  service:
    i % 5 === 3 ? "order-api" : i % 7 === 4 ? "auth-service" : "payment-api",
  level: i % 4 === 0 ? "ERROR" : i % 4 === 1 ? "WARN" : "INFO",
  message:
    i % 4 === 0
      ? "ConnectionPoolTimeout: timed out waiting for an available connection"
      : i % 4 === 1
        ? "Retry attempt 2/3 for payment capture request"
        : i % 5 === 3
          ? "Order status transition completed: pending → confirmed"
          : "Request completed successfully",
  trace: "a8f" + (92180 + i).toString(16) + "c2",
  env: i % 9 === 8 ? "staging" : "production",
  host: "payment-api-7d8f9b-x2k",
  request: "req_8af29" + i,
}));
export const navigation = [
  { name: "Home", icon: "Home", views: [] },
  {
    name: "My Work",
    icon: "CircleCheck",
    views: [
      "Today",
      "This Week",
      "Backlog",
      "Calendar",
      "Inbox",
      "My Activity",
    ],
  },
  {
    name: "Projects",
    icon: "Layers",
    views: ["Overview", "Issues", "Board", "Sprint", "Roadmap"],
  },
  {
    name: "Code",
    icon: "GitPullRequest",
    views: [
      "Merge Requests",
      "My Reviews",
      "Repositories",
      "Pipelines",
      "Architecture",
    ],
  },
  {
    name: "Observe",
    icon: "Activity",
    views: ["Overview", "Logs", "Dashboards", "Alerts", "Incidents"],
  },
  {
    name: "Docs",
    icon: "BookOpen",
    views: ["Home", "Spaces", "Recent", "Favorites"],
  },
  {
    name: "Settings",
    icon: "Settings",
    views: ["Integrations", "Notifications", "Workspace", "Preferences"],
  },
];
