export const orderDiff = [
  [" ", 'import { OrderStatus } from "./types";'],
  ["+", 'import { mapOrderStatus } from "./StatusMapper";'],
  [" ", ""],
  [" ", "export class OrderService {"],
  [" ", "  async getOrder(id: string): Promise<OrderResponse> {"],
  [" ", "    const order = await this.repository.findById(id);"],
  [" ", "    if (!order) throw new OrderNotFoundError(id);"],
  [" ", ""],
  [" ", "    return {"],
  [" ", "      id: order.id,"],
  ["-", "      status: order.status.toLowerCase(),"],
  ["+", "      status: mapOrderStatus(order.status),"],
  ["+", "      // Preserve the v2 response contract."],
  [" ", "      total: order.total,"],
  [" ", "      currency: order.currency,"],
  [" ", "      updatedAt: order.updatedAt.toISOString(),"],
  [" ", "    };"],
  [" ", "  }"],
  [" ", "}"],
];
export const fileDiffs = {
  "StatusMapper.ts": [
    ["+", 'import { OrderStatus, PublicStatus } from "./types";'],
    ["+", ""],
    ["+", "const STATUS_MAP: Record<OrderStatus, PublicStatus> = {"],
    ["+", '  PENDING: "pending",'],
    ["+", '  PAYMENT_CONFIRMED: "confirmed",'],
    ["+", '  FULFILLED: "fulfilled",'],
    ["+", '  REFUNDED: "refunded",'],
    ["+", '  CANCELLED: "cancelled",'],
    ["+", "};"],
    ["+", ""],
    ["+", "export function mapOrderStatus(status: OrderStatus) {"],
    ["+", "  const mapped = STATUS_MAP[status];"],
    ["+", "  if (!mapped) throw new UnknownOrderStatus(status);"],
    ["+", "  return mapped;"],
    ["+", "}"],
  ],
  "OrderController.ts": [
    [" ", '@Get(":id")'],
    [" ", 'async getOrder(@Param("id") id: string) {'],
    ["-", "  const order = await this.repository.findById(id);"],
    ["-", "  return this.mapResponse(order);"],
    ["+", "  return this.orderService.getOrder(id);"],
    [" ", "}"],
  ],
  "OrderService.test.ts": [
    ["+", 'describe("order status mapping", () => {'],
    ["+", '  it("maps a confirmed payment to confirmed", async () => {'],
    ["+", "    repository.findById.mockResolvedValue({"],
    ["+", '      ...orderFixture, status: "PAYMENT_CONFIRMED",'],
    ["+", "    });"],
    ["+", '    const order = await service.getOrder("order_128");'],
    ["+", '    expect(order.status).toBe("confirmed");'],
    ["+", '    expect(order.currency).toBe("KRW");'],
    ["+", "  });"],
    ["+", "});"],
  ],
  "PaymentController.ts": [
    [" ", '@Post("capture")'],
    [" ", "async capture(@Body() request: CaptureRequest) {"],
    ["+", "  if (!request.idempotencyKey) {"],
    ["+", '    throw new BadRequestException("Idempotency key required");'],
    ["+", "  }"],
    [" ", "  return this.paymentService.capture(request);"],
    [" ", "}"],
  ],
  "RetryQueue.ts": [
    ["+", "export class RetryQueue {"],
    ["+", "  async enqueue(request: RetryRequest) {"],
    ["+", "    const delay = Math.min(1000 * 2 ** request.attempt, 30000);"],
    ["+", '    await this.queue.add("payment.capture", request, {'],
    ["+", "      jobId: request.idempotencyKey,"],
    ["+", "      delay,"],
    ["+", "      attempts: 3,"],
    ["+", "    });"],
    ["+", "  }"],
    ["+", "}"],
  ],
  "PaymentWorker.ts": [
    [" ", "async process(job: Job<RetryRequest>) {"],
    ["+", "  const completed = await this.store.get(job.data.idempotencyKey);"],
    ["+", "  if (completed) return completed;"],
    [" ", "  try {"],
    [" ", "    return await this.gateway.capture(job.data);"],
    [" ", "  } catch (error) {"],
    ["+", "    if (job.attemptsMade >= 3) {"],
    ["+", "      await this.deadLetterQueue.add(job.data);"],
    ["+", "    }"],
    [" ", "    throw error;"],
    [" ", "  }"],
    [" ", "}"],
  ],
};
